const mongoose = require("mongoose");

const ResultSchema = new mongoose.Schema({
  SL_No: String,
  LETTER_NO: String,
  ROLL_NO: String,
  STUDENTS_NAME: String,
  FATHERS_NAME: String,
  MOBILE_NO: String,
  DISTRICT: String,
  APPEAR_DISTRICT: String,
  COURSE: String,
  VCOURSE_NAME: String,
  PRESENT_CLASS: String,
  NEXT_CLASS: String,
  COURSE_NAME: String,
  R: String,
  W_N_T: String,
  PERCENTAGE: String,
  W: String,
  FULL_MARKS: String,
  RANK: String,
  STATE_RANK: String,
  STATE_RANK_CASH_REWARD: String,
  CASH_REWARD: String,
  TOTAL_CASH_REWARD: String,
  SCHOLARSHIP_ON_BASE_FEE_AGE: String,
  SCHOLARSHIP_ON_TUITION_FEE_AGE: String,
  FOODING: String,
  LODGING: String,
  BASE_FEE: String,
  TUITION_FEE: String,
  TOTAL_FEE: String,
  GST_18: String,
  TOTAL_FEE_GST: String,
  SCHOLARSHIP_BASE_FEE: String,
  SCHOLARSHIP_TUTION_FEE: String,
  SCHOLARSHIP_FEE: String,
  FEE_AFTER_SCHOLARSHIP: String,
  FEE_AFTER_SCHOLARSHIP: String,
  TOTAL_FEE_AFTER_SCHOLARSHIP: String,
  GST_18: String,
  TOTAL_FEE_AFTER_SCHOLARSHIP_GST: String,
  REMARKS: String,
});

module.exports = mongoose.model("Result", ResultSchema);
